# Secrets - Sensitive Data (Base64 encoded)
# NOT: Production'da Azure Key Vault veya HashiCorp Vault kullanýn!
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend-services
  labels:
    app.kubernetes.io/name: backend-services
type: Opaque
data:
  # echo -n 'value' | base64
  JWT_SECRET_KEY: YWhmZ2ttY25oZmd5cnXEsW9wbGtzZ2Vyd3FobnZiY2dy  # ahfgkmcnhfgyruýoplksgerwqhnvbcgr
  SQL_SA_PASSWORD: RWtvb0AzMDAz  # Ekoo@3003
  SEQ_ADMIN_PASSWORD: YWRtaW4xMjM=  # admin123
---
# SQL Server Connection Strings
apiVersion: v1
kind: Secret
metadata:
  name: sql-connection-strings
  namespace: backend-services
type: Opaque
stringData:
  identity-db: "Server=sqlserver-service;Database=IdentityDb;User Id=sa;Password=Ekoo@3003;TrustServerCertificate=True"
  products-db: "Server=sqlserver-service;Database=ProductsDb;User Id=sa;Password=Ekoo@3003;TrustServerCertificate=True"
